In [1]:
import pandas as pd
import numpy as np

In [11]:
import sys
print(sys.executable)

/Library/Developer/CommandLineTools/usr/bin/python3

In [13]:
import seaborn as sns

tips = sns.load_dataset("tips")

print(tips.columns)

ModuleNotFoundError: No module named 'seaborn'

In [29]:
tips= pd.read_csv('/Users/prishitasingh/Desktop/Machine Learning/pandas/bookings.csv')

print(tips.shape)

(12, 5)

In [8]:
tips.groupby("day").agg(
    booking_count=("booking_id", "size"),
    avg_party_size=("party_size", "mean")
)

     booking_count  avg_party_size
day
Fri              2        4.000000
Sat              6        3.500000
Sun              4        3.666667

In [12]:
import seaborn as sns

tips = sns.load_dataset("tips")

ModuleNotFoundError: No module named 'seaborn'

In [5]:
print(tips.columns)

Index(['booking_id', 'customer', 'day', 'time', 'party_size'], dtype='object')

In [15]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [16]:
import sys
!{sys.executable} -m pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 1.2 MB/s eta 0:00:01
Collecting matplotlib!=3.6.1,>=3.4
  Downloading matplotlib-3.9.4-cp39-cp39-macosx_11_0_arm64.whl (7.8 MB)
     |████████████████████████████████| 7.8 MB 72 kB/s eta 0:00:0121
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Collecting pillow>=8
  Downloading pillow-11.3.0-cp39-cp39-macosx_11_0_arm64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 149 kB/s eta 0:00:01
Collecting importlib-resources>=3.2.0
  Downloading importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.60.2-cp39-cp39-macosx_10_9_universal2.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 238 kB/s eta 0:00:01
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
     |████████████████████████████████| 122 kB 95 kB/s eta 0:00:011
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.7-cp39-cp39-macosx_11_0_arm64.whl (64 kB)
     |████████████████████████████████| 64 kB 403 kB/s eta 0:00:01
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.0-cp39-cp39-macosx_11_0_arm64.whl (249 kB)
     |████████████████████████████████| 249 kB 631 kB/s eta 0:00:01
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Requirement already satisfied: packaging>=20.0 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: zipp>=3.1.0 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: pytz>=2020.1 in /Users/prishitasingh/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2026.3.post1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.15.0)
Installing collected packages: pyparsing, pillow, kiwisolver, importlib-resources, fonttools, cycler, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.3.0 cycler-0.12.1 fonttools-4.60.2 importlib-resources-6.5.2 kiwisolver-1.4.7 matplotlib-3.9.4 pillow-11.3.0 pyparsing-3.3.2 seaborn-0.13.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [17]:
import seaborn as sns

tips = sns.load_dataset("tips")

print(tips.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [18]:
tips.groupby("day").agg(
    Bill_count=("total_bill", "size"),
    avg_bill=("total_bill", "mean"),
    avg_tip=("tip", "mean")
).round(2)

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/58599438.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby("day").agg(

      Bill_count  avg_bill  avg_tip
day
Thur          62     17.68     2.77
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Sun           76     21.41     3.26

In [ ]:
tips.groupby("day").agg(
    Bill_count=("total_bill", "size"),
    avg_bill=("total_bill", "mean"),
    avg_tip=("tip", "mean")
).round(2)

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/2697432631.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby("day").agg(

      Bill_count  avg_bill  avg_tip
day
Thur          62     17.68     2.77
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Sun           76     21.41     3.26

In [22]:
summary = tips.groupby("day").agg(
    Bill_count=("total_bill", "size"),
    avg_bill=("total_bill", "mean"),
    avg_tip=("tip", "mean")
).round(2)

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/1947427784.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = tips.groupby("day").agg(

In [23]:
summary.columns

Index(['Bill_count', 'avg_bill', 'avg_tip'], dtype='object')

In [24]:
print(summary.columns)

Index(['Bill_count', 'avg_bill', 'avg_tip'], dtype='object')

In [25]:
print(summary.columns.tolist())
print(summary.index)

['Bill_count', 'avg_bill', 'avg_tip']
CategoricalIndex(['Thur', 'Fri', 'Sat', 'Sun'], categories=['Thur', 'Fri', 'Sat', 'Sun'], ordered=False, dtype='category', name='day')

In [27]:
flat=summary.reset_index()
print(flat.columns.tolist())
flat.head()

['day', 'Bill_count', 'avg_bill', 'avg_tip']

    day  Bill_count  avg_bill  avg_tip
0  Thur          62     17.68     2.77
1   Fri          19     17.15     2.73
2   Sat          87     20.44     2.99
3   Sun          76     21.41     3.26

In [32]:
summary.to_csv("Report.csv")
flat = pd.read_csv("Report.csv")
flat.head()

    day  Bill_count  avg_bill  avg_tip
0  Thur          62     17.68     2.77
1   Fri          19     17.15     2.73
2   Sat          87     20.44     2.99
3   Sun          76     21.41     3.26

In [38]:
import seaborn as sns

tips = sns.load_dataset("tips")

print(tips.columns.tolist())

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [39]:
smoker_report = tips.groupby("smoker").agg(
    total_bill=("total_bill", "size"),
    avg_bill=("total_bill", "mean"),
    avg_tip=("tip", "mean")
)

smoker_report

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/2461422117.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  smoker_report = tips.groupby("smoker").agg(

        total_bill   avg_bill   avg_tip
smoker
Yes             93  20.756344  3.008710
No             151  19.188278  2.991854

In [41]:
smoker_report.reset_index().to_csv("smoker_report.csv", index=False)

In [42]:
temp = pd.read_csv("smoker_report.csv")
temp.head()

  smoker  total_bill   avg_bill   avg_tip
0    Yes          93  20.756344  3.008710
1     No         151  19.188278  2.991854

In [43]:
tips = pd.read_csv("bookings.csv")

In [44]:
tips = sns.load_dataset("tips")

In [45]:
bookings = pd.read_csv("bookings.csv")
tips = sns.load_dataset("tips")

In [46]:
bookings.groupby("day").agg(
    booking_count=("booking_id", "size"),
    avg_party_size=("party_size", "mean")
)

     booking_count  avg_party_size
day
Fri              2        4.000000
Sat              6        3.500000
Sun              4        3.666667

In [47]:
tips.groupby("smoker").agg(
    total_bill=("total_bill", "size"),
    avg_bill=("total_bill", "mean"),
    avg_tip=("tip", "mean")
)

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/1816163231.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby("smoker").agg(

        total_bill   avg_bill   avg_tip
smoker
Yes             93  20.756344  3.008710
No             151  19.188278  2.991854

In [48]:
smoker_report=tips.groupby('smoker').agg(
    total_bill=("total_bill",'size'),
    avg_bill=("total_bill","mean"),
    avg_tip=("tip",'mean')
)
smoker_report.reset_index().to_csv("smoker_report.csv",index=False)
temp=pd.read_csv("smoker_report.csv")
temp.head()

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/1067997736.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  smoker_report=tips.groupby('smoker').agg(

  smoker  total_bill   avg_bill   avg_tip
0    Yes          93  20.756344  3.008710
1     No         151  19.188278  2.991854

In [53]:
print(tips.groupby("day")['tip'].idxmax())
print(tips.groupby("day")['tip'].max())

day
Thur    141
Fri      95
Sat     170
Sun     183
Name: tip, dtype: int64
day
Thur     6.70
Fri      4.73
Sat     10.00
Sun      6.50
Name: tip, dtype: float64

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/525368670.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips.groupby("day")['tip'].idxmax())
/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/525368670.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips.groupby("day")['tip'].max())

In [50]:
tips.groupby("day")['tip'].max()

/var/folders/yt/n_1y0wdj5s32bsrm17h2xnbc0000gn/T/ipykernel_99624/784064157.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby("day")['tip'].max()

day
Thur     6.70
Fri      4.73
Sat     10.00
Sun      6.50
Name: tip, dtype: float64

In [56]:
bookings.nunique()

print(bookings['customer'].str.lower().str.strip())

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: object

In [58]:
bookings['customer'] = bookings['customer'].str.lower() \
    .str.strip().str.split().str.join(" ")